### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Mendim** [rkubik/paypark#1]
92.53.49.176 - - [07/Jul/2018 12:23:17] "GET / HTTP/1.1" 302 -
/var/paypark/paypark/frontend/auth.py:13: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = LoginForm()
[2018-07-07 12:23:17,781] ERROR in app: Exception on /auth/login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/paypark/paypark/frontend/auth.py", line 14, in auth_login
    if current_user.is_authenticated() or form.validate_on_submit():
TypeError: 'bool' object is not callable
92.53.49.176 - - [07/Jul/2018 12:23:17] "GET /auth/login HTTP/1.1" 500 -

**Comment by rkubik** [comment]
Thanks @Mendim. This should be fixed by https://github.com/rkubik/paypark/commit/0913e4dbc06d36e3f409f627a85937b9e9641c15 and https://github.com/rkubik/paypark/commit/7bd7c7ecb581695b99afffbe8ac49629e1febf43.

**Comment by Mendim** [comment]
Thank you.i just fixed it.it was a problem with flask updates
I need a advanced parking by sms system.can we talk for a development.I have some requirements
can u send me your mail to   info (at) mendim.com
